[project]
name = "growthbrief"
version = "0.1.0"
description = "Experimental portfolio + AI analysis toolkit"
requires-python = ">=3.11, <3.12"
dependencies = []
[[project.authors]]
name = "Jeff (and Personas)"

